name: Container CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  docker-test:
    name: Docker Image Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t qa-tests:latest .

      - name: Run API tests in container
        run: docker run qa-tests:latest pytest tests/api -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1

      - name: Run UI tests in container
        run: docker run qa-tests:latest pytest tests/ui -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1

      - name: Run DB tests in container
        run: docker run qa-tests:latest pytest tests/db -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1

      - name: Run Smoke tests in container
        run: docker run qa-tests:latest pytest tests/ -m smoke -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1

      - name: Run Regression tests in container
        run: docker run qa-tests:latest pytest tests/ -m regression -n auto --alluredir=allure-results --reruns 2 --reruns-delay 1

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-regression
          path: allure-results

  compose-test:
    name: Docker Compose Test
    runs-on: ubuntu-latest
    needs: docker-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run with Docker Compose
        run: docker compose up --build --abort-on-container-exit

      - name: Cleanup
        if: always()
        run: docker compose down -v
