name: E-Commerce QA Framework

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run smoke tests
        run: pytest tests/ -v -m smoke
        env:
          BASE_URL: https://fakestoreapi.com

  regression-tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: smoke-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run regression tests
        run: pytest tests/ -v -m regression
        env:
          BASE_URL: https://fakestoreapi.com
